### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by 222464** [GreenWaves-Technologies/gap8_openocd#1]
Hi,

I tried following the instructions in the gap_sdk repository, which includes compiling gap8_openocd.
When I got to the make step, I get the following compilation error:

`error: ‘ftdi_usb_purge_buffers’ is deprecated [-Werror=deprecated-declarations]`

In presto.c and openjtag.c.

I can just disable the deprecation, and see if it works then, but I thought you should know.

OS: Manjaro Linux

**Comment by Yaooooo** [comment]
Hi,

I took a look in google about this problem, for example, 
https://www.mail-archive.com/openocd-devel@lists.sourceforge.net/msg13024.html
https://www.eclipse.org/forums/index.php/t/1099250/

The problem seems it's because the openOCD is not compatible with the libftdi you have.

This is the version I have:
libftdi-dev is already the newest version (0.20-4build8).
libftdi1 is already the newest version (0.20-4build8).

You can try to install this version of libftdi then. If this cannot resolve your problem, you may need to ask this in openOCD forum.

Officially, we support our SDK only for Ubuntu 16 - 20.
For other OS, I am sorry that we don't have energy to maintain them.

**Comment by 222464** [comment]
Thanks for the quick response!

I was able to compile it by just disabling the deprecation. That resulted in the following modified configure step:

`./configure --program-prefix=gap8- --prefix=/usr --datarootdir=/usr/share/gap8-openocd CFLAGS='-Wno-deprecated -Wno-deprecated-declarations' CXXFLAGS='-Wno-deprecated -Wno-deprecated-declarations'`

I realize that only Ubuntu is supported, I am going to try anyway though, and see how far I get!
I can let you know of any fixes and workarounds that are needed (if I get it to work), if you like.
